<?php

namespace App\Http\Controllers;

use App\Models\Account;
use App\Models\Login;
use App\Models\OnboardingTemplate;
use App\Models\Task;
use App\Models\User;
use App\Models\Vendor;
use App\Support\Contracts\TenantResolver;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;

/**
 * Onboarding v2.
 *
 * The template is per-company JSON (paste your SOP once). The RUN is atomic:
 * one transaction creates the person, one credential per picked vendor (passwords
 * generated by the company formula, stored in the registry — never displayed in a
 * task), floating-account assignments, and an "Onboard {name}" task project whose
 * steps are chained and planned around the start date. Abandoning the form leaves
 * ZERO residue — the old wizard's half-created users can't happen.
 */
class OnboardingController extends Controller
{
    /** Every template the company has, plus which starters exist for empty kinds. */
    public function template(Request $request): JsonResponse
    {
        $companyId = app(TenantResolver::class)->id();
        $kind = $request->string('kind')->toString() ?: 'onboarding';
        $variant = $request->string('variant')->toString();

        $all = OnboardingTemplate::query()->where('company_id', $companyId)
            ->get(['kind', 'variant', 'name']);
        $t = OnboardingTemplate::query()->where('company_id', $companyId)
            ->where('kind', $kind)->where('variant', $variant)->first();
        $source = $t?->source_page_id ? \App\Models\DocPage::query()->find($t->source_page_id, ['id', 'title']) : null;

        return response()->json([
            'company_id' => $companyId,
            'kinds' => \App\Support\StarterTemplates::KINDS,
            'existing' => $all,           // [{kind, variant, name}]
            'kind' => $kind, 'variant' => $variant,
            'name' => $t->name ?? \App\Support\StarterTemplates::KINDS[$kind] ?? 'Onboarding',
            'steps' => $t ? json_decode($t->steps, true) : null,
            'sop_meta' => $t ? (json_decode($t->steps, true)['meta'] ?? null) : null,
            'source' => $source ? ['id' => $source->id, 'title' => $source->title] : null,
        ]);
    }

    /**
     * Adopt a shipped starter: it materializes as a real Docs page (the master —
     * rich text, editable in Docs) and the template is parsed FROM that page.
     * From then on the loop is: edit the doc, re-parse.
     */
    public function adoptStarter(Request $request): JsonResponse
    {
        abort_if(auth()->user()?->role === 'User', 403);
        $companyId = app(TenantResolver::class)->id();
        abort_if(! $companyId, 422, 'Pick a company first.');

        $data = $request->validate([
            'kind' => 'required|in:onboarding,offboarding,imaging,eprotection',
            'variant' => 'nullable|string|max:100',
        ]);
        $variant = $data['variant'] ?? '';
        $tpl = \App\Support\StarterTemplates::get($data['kind'], $variant);
        abort_if(! $tpl, 404);

        $title = (\App\Support\StarterTemplates::KINDS[$data['kind']] ?? 'SOP') . ($variant ? " — {$variant}" : '') . ' SOP';
        $page = \App\Models\DocPage::create([
            'company_id' => $companyId,
            'space_id' => \App\Models\Space::query()->orderBy('position')->value('id'),
            'title' => $title,
            'body' => \App\Support\SopDocParser::toHtml($tpl['steps']),
            'category' => 'SOP',
            'updated_by' => auth()->id(),
        ]);

        $t = OnboardingTemplate::updateOrCreate(
            ['company_id' => $companyId, 'kind' => $data['kind'], 'variant' => $variant],
            ['name' => $title, 'steps' => json_encode(\App\Support\SopDocParser::parse($page->body)), 'source_page_id' => $page->id],
        );

        return response()->json(['ok' => true, 'page_id' => $page->id, 'template_id' => $t->id]);
    }

    /** Compile a template from an existing Docs page — the page becomes its master. */
    public function parseFromDoc(Request $request): JsonResponse
    {
        abort_if(auth()->user()?->role === 'User', 403);
        $companyId = app(TenantResolver::class)->id();
        abort_if(! $companyId, 422, 'Pick a company first.');

        $data = $request->validate([
            'page_id' => 'required|integer|exists:doc_pages,id',
            'kind' => 'required|in:onboarding,offboarding,imaging,eprotection',
            'variant' => 'nullable|string|max:100',
        ]);
        $page = \App\Models\DocPage::query()->findOrFail($data['page_id']);
        $parsed = \App\Support\SopDocParser::parse($page->body ?? '');
        abort_if(empty($parsed['steps']), 422, 'Nothing parseable on that page.');

        $t = OnboardingTemplate::updateOrCreate(
            ['company_id' => $companyId, 'kind' => $data['kind'], 'variant' => $data['variant'] ?? ''],
            ['name' => $page->title, 'steps' => json_encode($parsed), 'source_page_id' => $page->id],
        );

        return response()->json(['ok' => true, 'steps' => $parsed, 'source' => ['id' => $page->id, 'title' => $page->title]]);
    }

    /** Docs pages as {id,label} for the SOP picker. */
    public function docOptions(): JsonResponse
    {
        return response()->json(
            \App\Models\DocPage::query()->orderBy('title')->get(['id', 'title'])
                ->map(fn ($p) => ['id' => $p->id, 'label' => $p->title])
        );
    }

    /**
     * Preview what a runbook generates — the flat task list a machine would get,
     * with /references resolved to their current steps. This is "see it in action"
     * without onboarding a real machine.
     */
    public function preview(Request $request): JsonResponse
    {
        $companyId = app(TenantResolver::class)->id();
        $kind = $request->string('kind')->toString() ?: 'imaging';
        $variant = $request->string('variant')->toString();
        $t = OnboardingTemplate::query()->where('company_id', $companyId)
            ->where('kind', $kind)->where('variant', $variant)->first();
        abort_if(! $t, 404);
        $steps = json_decode($t->steps, true)['steps'] ?? [];
        $base = $request->getSchemeAndHttpHost();

        $rows = [];
        foreach ($steps as $step) {
            $refExtra = [];
            $note = '';
            foreach (['why' => 'Why', 'instructions' => 'How', 'done_when' => 'Done when'] as $k => $label) {
                if (! empty($step[$k])) {
                    [$resolved, $extra] = \App\Support\RunbookRefs::resolve($step[$k], $companyId, $base);
                    if ($k === 'instructions') $note = $resolved;
                    $refExtra = array_merge($refExtra, $extra);
                }
            }
            $rows[] = ['title' => $step['title'], 'note' => $note, 'depth' => 0, 'ref' => false];
            // referenced runbook's live steps
            foreach ($refExtra as $r) {
                $rows[] = ['title' => $r['title'], 'note' => $r['instructions'] ?? '', 'depth' => 1, 'ref' => true];
            }
            foreach ($step['subtasks'] ?? [] as $sub) {
                $rows[] = ['title' => $sub['title'], 'note' => $sub['instructions'] ?? '', 'depth' => 1, 'ref' => false];
            }
        }
        return response()->json(['rows' => $rows]);
    }

    public function saveTemplate(Request $request): JsonResponse
    {
        abort_if(auth()->user()?->role === 'User', 403);
        $companyId = app(TenantResolver::class)->id();
        abort_if(! $companyId, 422, 'Pick a company first — templates are per company.');

        $data = $request->validate([
            'name' => 'nullable|string|max:255',
            'kind' => 'nullable|in:onboarding,offboarding,imaging,eprotection',
            'variant' => 'nullable|string|max:100',
            'steps' => 'required|array',
            'steps.version' => 'required|integer',
            'steps.steps' => 'required|array',
        ]);

        $kind = $data['kind'] ?? 'onboarding';
        $t = OnboardingTemplate::updateOrCreate(
            ['company_id' => $companyId, 'kind' => $kind, 'variant' => $data['variant'] ?? ''],
            ['name' => $data['name'] ?? (\App\Support\StarterTemplates::KINDS[$kind] ?? 'Onboarding'), 'steps' => json_encode($data['steps'])],
        );

        return response()->json(['ok' => true, 'id' => $t->id]);
    }

    /** The wizard. One transaction; everything or nothing. */
    public function run(Request $request): JsonResponse
    {
        abort_if(auth()->user()?->role === 'User', 403);
        $companyId = app(TenantResolver::class)->id();
        abort_if(! $companyId, 422, 'Pick a company first.');

        $data = $request->validate([
            'first' => 'required|string|max:255',
            'last' => 'required|string|max:255',
            'username' => 'nullable|string|max:255',
            'email' => 'required|email|max:255|unique:users,email',
            'title' => 'nullable|string|max:255',
            'department' => 'nullable|string|max:255',
            'start_date' => 'required|date',
            'vendor_ids' => 'nullable|array',
            'vendor_ids.*' => 'integer|exists:vendors,vendorID',
            'account_ids' => 'nullable|array',          // floating accounts to assign
            'account_ids.*' => 'integer|exists:accounts,id',
        ]);

        $template = OnboardingTemplate::query()->where('company_id', $companyId)
            ->where('kind', 'onboarding')
            ->whereIn('variant', array_filter(['', $data['department'] ?? null], fn ($v) => $v !== null))
            ->orderByRaw("variant <> '' DESC")   // department variant wins over the default
            ->first();
        $steps = $template ? (json_decode($template->steps, true)['steps'] ?? []) : [];
        $doh = Carbon::parse($data['start_date']);
        $company = \App\Models\Company::find($companyId);

        $result = DB::transaction(function () use ($data, $steps, $doh, $company, $companyId) {
            // 1. The person — a directory record; sign-in stays a separate, deliberate grant.
            $person = User::create([
                'name' => $data['first'], 'last' => $data['last'],
                'username' => $data['username'] ?? null,
                'email' => $data['email'],
                'title' => $data['title'] ?? null, 'department' => $data['department'] ?? null,
                'company_id' => $companyId,
                'role' => 'User', 'active' => true, 'can_login' => false,
                'password' => Hash::make(str()->random(40)),   // unusable placeholder; can_login gates anyway
            ]);

            // 2. One credential per picked vendor, password by the company formula
            //    (base for Domain/Microsoft, last-2-chars variant for the rest — the
            //    format is deliberate and preserved). Stored ONCE, here, in the registry.
            $base = $this->generatePassword($data['first'], $data['last'], $company?->name);
            $credentials = [];
            foreach (Vendor::query()->whereIn('vendorID', $data['vendor_ids'] ?? [])->get() as $vendor) {
                $isDirectory = (bool) preg_match('/active directory|domain/i', $vendor->name);
                $isBaseHolder = $isDirectory || preg_match('/microsoft/i', $vendor->name);
                $login = Login::create([
                    'company_id' => $companyId,
                    'vendorID' => $vendor->vendorID,
                    'login_name' => $vendor->name,
                    'login_id' => $isDirectory ? ($data['username'] ?: $data['email']) : $data['email'],
                    'login_pass' => $isBaseHolder ? $base : $this->variantPassword($base),
                    'sharing' => 'personal',
                    'notes' => 'Created during onboarding v2',
                    'is_active' => 1,
                    'userID' => $person->id,               // legacy column; ITer reads it
                ]);
                $login->holders()->attach($person->id);
                $credentials[] = ['vendor' => $vendor->name, 'vendor_id' => $vendor->vendorID, 'login_id' => $login->login_id];
            }

            // 3. Floating accounts they'll hold from day one.
            $floating = [];
            foreach (Account::query()->whereIn('id', $data['account_ids'] ?? [])->get() as $account) {
                $account->holders()->syncWithoutDetaching([$person->id]);
                $floating[] = $account->identifier;
            }

            // 4. The task project — the human checklist, chained and planned off the DOH.
            // A task's notes carry the whole playbook card — bench mode reads these.
            $card = function (array $step) use (&$sub) {
                $parts = [];
                foreach (['why' => 'Why', 'instructions' => 'How', 'done_when' => 'Done when', 'record' => 'Record'] as $k => $label) {
                    if (! empty($step[$k])) $parts[] = $label . ': ' . $sub($step[$k]);
                }
                return implode("\n", $parts);
            };
            $sub = fn ($s) => str_replace(
                ['{first}', '{last}', '{username}', '{email}', '{start_date}', '{local_domain}', '{domain}'],
                [$data['first'], $data['last'], $data['username'] ?? '', $data['email'], $doh->toDateString(),
                 $company?->local_domain ?? '', $company?->domain ?? ''],
                $s ?? ''
            );
            $monday = fn (Carbon $d) => max($d->copy()->startOfWeek(Carbon::MONDAY), Carbon::now()->startOfWeek(Carbon::MONDAY))->toDateString();
            $ord = (int) (Task::query()->max('ord') + 1);

            $project = Task::create([
                'title' => "Onboard {$data['first']} {$data['last']}",
                'is_project' => true, 'status' => 'In progress',
                'week' => $monday(Carbon::now()), 'origin' => Carbon::now()->toDateString(),
                'notes' => "DOH {$doh->toDateString()} · {$data['email']}" . ($floating ? ' · floating: ' . implode(', ', $floating) : ''),
                'assigned_to' => auth()->id(), 'ord' => $ord++,
            ]);

            $mkTask = function (array $attrs) use (&$ord, $project) {
                return Task::create($attrs + [
                    'parent_id' => $attrs['parent_id'] ?? $project->id,
                    'assigned_to' => auth()->id(), 'ord' => $ord++,
                ]);
            };

            $taskCount = 0;
            // Vendor-account tasks: parallel, pre-arrival. Credentials are ALREADY in the
            // registry — the task is doing it in the real console, not inventing secrets.
            foreach ($credentials as $c) {
                $when = $doh->copy()->subDays(2);
                $mkTask([
                    'title' => "Create {$c['vendor']} account — {$c['login_id']}",
                    'notes' => 'Credentials are generated and stored in the registry. Create the account in the console using them; never write them anywhere else.',
                    'week' => $monday($when), 'origin' => Carbon::now()->toDateString(),
                    'planned_start' => $when->toDateString(), 'due_date' => $when->toDateString(),
                ]); $taskCount++;
            }
            if ($floating) {
                $mkTask([
                    'title' => 'Hand over floating accounts: ' . implode(', ', $floating),
                    'notes' => 'Assigned in the registry; walk them through retrieval and usage.',
                    'week' => $monday($doh), 'origin' => Carbon::now()->toDateString(),
                    'planned_start' => $doh->toDateString(), 'due_date' => $doh->toDateString(),
                ]); $taskCount++;
            }

            // Template steps: chained sequentially; subtasks ride under their step.
            $prev = null;
            foreach ($steps as $step) {
                $when = $doh->copy()->addDays((int) ($step['offset_days'] ?? 0));
                $t = $mkTask([
                    'title' => $sub($step['title']),
                    'notes' => $card($step),
                    'week' => $monday($when), 'origin' => Carbon::now()->toDateString(),
                    'planned_start' => $when->toDateString(), 'due_date' => $when->toDateString(),
                    'depends_on_id' => $prev?->id,
                ]); $taskCount++;
                foreach ($step['subtasks'] ?? [] as $s) {
                    $whenS = $doh->copy()->addDays((int) ($s['offset_days'] ?? ($step['offset_days'] ?? 0)));
                    $mkTask([
                        'title' => $sub($s['title']),
                        'notes' => $card($s),
                        'parent_id' => $t->id,
                        'week' => $monday($whenS), 'origin' => Carbon::now()->toDateString(),
                        'planned_start' => $whenS->toDateString(), 'due_date' => $whenS->toDateString(),
                    ]); $taskCount++;
                }
                $prev = $t;
            }

            Log::info('onboarding.run', ['person' => $person->id, 'by' => auth()->id(),
                'credentials' => count($credentials), 'floating' => count($floating), 'tasks' => $taskCount]);

            return [
                'person_id' => $person->id,
                'project_id' => $project->id,
                'credentials' => $credentials,
                'floating' => $floating,
                'tasks' => $taskCount,
            ];
        });

        // Provisioning fires AFTER the transaction: an API outage can never roll back
        // the hire. Success completes the task with a note; failure leaves the manual
        // task with the error attached. Automation accelerates, never gates.
        foreach ($result['credentials'] as $i => $c) {
            $vendor = Vendor::query()->find($c['vendor_id']);
            $plug = $vendor ? \App\Support\Provisioning\ProvisionerRegistry::for($vendor, $companyId) : null;
            if (! $plug) continue;
            [$prov, $config] = $plug;
            $task = Task::query()->where('parent_id', $result['project_id'])
                ->where('title', 'like', "Create {$c['vendor']} account%")->first();
            try {
                $summary = $prov->provision($config, $data);
                $result['credentials'][$i]['provisioned'] = true;
                $task?->update(['done' => true, 'pct' => 100, 'completed_at' => Carbon::now(),
                    'notes' => trim(($task->notes ?? '') . "\n\nAuto-provisioned via API: {$summary}")]);
                Log::info('onboarding.provisioned', ['vendor' => $c['vendor'], 'person' => $result['person_id']]);
            } catch (\Throwable $e) {
                $result['credentials'][$i]['provisioned'] = false;
                $task?->update(['notes' => trim(($task->notes ?? '') . "\n\nAPI attempt failed — create manually. " . $e->getMessage())]);
                Log::warning('onboarding.provision_failed', ['vendor' => $c['vendor'], 'error' => $e->getMessage()]);
            }
        }

        return response()->json($result, 201);
    }

    /**
     * Company password formula — Xy-YYYYMMDD-AB@! — kept EXACTLY as specified in the
     * legacy wizard ("DO NOT CHANGE THIS PASSWORD LOGIC"). Generated once per run,
     * stored in the registry; variants change only the last two special characters.
     */
    private function generatePassword(string $first, string $last, ?string $companyName): string
    {
        $date = now()->format('Ymd');
        $initials = strtoupper(substr($first, 0, 1) . substr($last, 0, 1));
        if ($companyName) {
            $ci = substr($companyName, 0, 2);
            $company = rand(0, 1) ? strtoupper($ci[0]) . strtolower($ci[1]) : strtolower($ci[0]) . strtoupper($ci[1]);
        } else {
            $company = 'Xx';
        }
        return $company . '-' . $date . '-' . $initials . $this->twoSpecials();
    }

    private function variantPassword(string $base): string
    {
        return substr($base, 0, -2) . $this->twoSpecials();
    }

    private function twoSpecials(): string
    {
        $chars = '!@#$%^&()';
        return $chars[rand(0, strlen($chars) - 1)] . $chars[rand(0, strlen($chars) - 1)];
    }
}
